<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('bootstrap/css/bootstrap.min.css'))
                        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css')
                        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css')
						->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
						->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
						->prependStylesheet($this->basePath('plugins/iCheck/flat/blue.css'))
						->prependStylesheet($this->basePath('plugins/morris/morris.css'))
						->prependStylesheet($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.css'))
						->prependStylesheet($this->basePath('plugins/datepicker/datepicker3.css'))
						->prependStylesheet($this->basePath('plugins/daterangepicker/daterangepicker.css'))
						->prependStylesheet($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'));

        ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
	    <div class="wrapper">

          	<?= $this->adminheader?>
            <!-- Content Wrapper. Contains page content -->
  			<div class="content-wrapper">
            <?= $this->sidebar?>
			<?= $this->Success();?>
			<?= $this->Error();?>
            <?= $this->content; ?>
            </div>
			<?= $this->footer; ?>            
            <div class="control-sidebar-bg"></div>
        </div>
	<?= $this->inlineScript()
    ->prependFile($this->basePath('plugins/jQuery/jquery-2.2.3.min.js'))
    ->prependFile('https://code.jquery.com/ui/1.11.4/jquery-ui.min.js')
    ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')
    ->prependFile($this->basePath('plugins/morris/morris.min.js'))
    ->prependFile($this->basePath('plugins/sparkline/jquery.sparkline.min.js'))
    ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
    ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
    ->prependFile($this->basePath('plugins/knob/jquery.knob.js'))
    ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js')
    ->prependFile($this->basePath('plugins/daterangepicker/daterangepicker.js'))
    ->prependFile($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
    ->prependFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))
    ->prependFile($this->basePath('plugins/fastclick/fastclick.js'))
    ->prependFile($this->basePath('dist/js/app.min.js'))
    ->prependFile($this->basePath('dist/js/pages/dashboard.js'))
    ->prependFile($this->basePath('plugins/fastclick/fastclick.js'))
    ->prependFile($this->basePath('plugins/fastclick/fastclick.js'))
    ->prependFile($this->basePath('bootstrap/js/bootstrap.min.js'));
		 ?>
    </body>
</html>
