<div class="login-box">

  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>


                <?php
                $form->prepare();
                $form->setAttribute('action', $this->url('login'));
                echo $this->form()->openTag($form);
                ?>
                <?php echo $this->formInput( $form->get('secureprefix')->setAttribute( 'value' , $this->SecureKey() ) ); ?>
              <div class="form-group">
                
                <label for="exampleInputEmail1">Username</label>
                <?php echo $this->formelement( $form->get('userlogin') )?>
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
              </div>
              <div class="form-group has-feedback">
                <label for="exampleInputPassword1">Password</label>
                <?php echo $this->formelement( $form->get('pw') )?>
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
              </div>
              <button type="submit" class="btn btn-default">Login</button>
            <?php echo $this->form()->closeTag($form)?>

	</div>
</div>